# 配置文件
#spring:
#  profiles:
#    active: @build.env@


server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://192.168.31.38:3306/blog_helper_dev?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis:
mybatis-plus:
  mapper-locations: classpath:com/wxhao/blog/server/mapping/*

# 自定义配置
hao:
  env-info:
    env-name: local
    server-name: blog-helper
  snowflake:
    data-center-id: 11
    worker-id: 1

qn:
  access-key:
  secretKey:
  bucket:
  zoneName:
  urlPrefix: